name: SBOM for existing Docker images

on:
  workflow_dispatch:   # lo lanci a mano quando ti serve

permissions:
  contents: read
  security-events: write

jobs:
  sbom-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Pull Guacamole image
        run: |
          docker pull ghcr.io/cytrix-italia/guacamole-server/guacamole-guacd:latest
          docker pull ghcr.io/cytrix-italia/guacamole-server/guacamole-guacamole:latest 
          docker pull ghcr.io/cytrix-italia/guacamole-server/mysql:latest

      # Genera SBOM per guacamole-guacamole
      - name: SBOM for guacamole-guacamole
        uses: anchore/sbom-action@v0
        with:
           image: ghcr.io/cytrix-italia/guacamole-server/guacamole-guacamole:latest
           format: spdx-json
           output-file: sbom-guacamole.json
           upload-artifact: false

      # Genera SBOM per guacamole-guacd
      - name: SBOM for guacamole-guacd
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/cytrix-italia/guacamole-server/guacamole-guacd:latest
          format: spdx-json
          output-file: sbom-guacd.json
          upload-artifact: false

      # Genera SBOM per mysql
      - name: SBOM for mysql
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/cytrix-italia/guacamole-server/mysql:latest
          format: spdx-json
          output-file: sbom-mysql.json
          upload-artifact: false

      - name: Upload all SBOMs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-sboms
          path: |
            sbom-guacamole.json
            sbom-guacd.json
            sbom-mysql.json

      - name: Submit SBOM for guacamole-guacamole
        uses: anchore/sbom-action@v0
        with:
           image: ghcr.io/cytrix-italia/guacamole-server/guacamole-guacamole:latest
           github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Submit SBOM for guacamole-guacd
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/cytrix-italia/guacamole-server/guacamole-guacd:latest
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Submit SBOM for mysql
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/cytrix-italia/guacamole-server/mysql:latest
          github-token: ${{ secrets.GITHUB_TOKEN }}

