# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: trivy

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '15 12 * * 2'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }} 

      - name: Pull Guacamole image
        run: |
          docker pull ghcr.io/cytrix-italia/guacamole-server/guacamole-guacd:latest
          docker pull ghcr.io/cytrix-italia/guacamole-server/guacamole-guacamole:latest 
          docker pull ghcr.io/cytrix-italia/guacamole-server/mysql:latest
      

      - name: Run Trivy vulnerability scanner guad
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'ghcr.io/cytrix-italia/guacamole-server/guacamole-guacd:latest'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-guacd.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
      
      - name: Run Trivy vulnerability scanner guacamole
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'ghcr.io/cytrix-italia/guacamole-server/guacamole-guacamole:latest'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-guacamole.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Run Trivy vulnerability scanner MySql
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'ghcr.io/cytrix-italia/guacamole-server/mysql:latest'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-mysql.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Upload Trivy scan results Guacd
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-guacd.sarif'
          category: 'trivy-guacd'

      - name: Upload Trivy scan results Guacamole
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-guacamole.sarif'
          category: 'trivy-guacamole'

      - name: Upload Trivy scan results MySQL
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-mysql.sarif'
          category: 'trivy-mysql'
